# Valkyrie — Awakening — bundle: default
# Auto-created by seed_class_shells.

class: Valkyrie
spec: Awakening
bundle_id: default
name: Default
description: ''
locked_skills: []
hotbar_skills: []
core_skill: {}
skill_addons:
  pve: []
