# Guardian — Succession — bundle: default
# Auto-created by seed_class_shells.

class: Guardian
spec: Succession
bundle_id: default
name: Default
description: ''
locked_skills: []
hotbar_skills: []
core_skill: {}
skill_addons:
  pve: []
